### ISSUE TITLE
Support conditional modifiers

### ISSUE THREAD

**Issue by emattias** [emberjs/ember-render-modifiers#22]
Since (to my knowledge) its not possible to conditionally add a modifier. Something like this:

```hbs
// doesnt work
<div
  {{if @onInsertTextArea (did-insert @onInsertTextArea)}}
/>
```

```hbs
// doesnt work
<div
  {{#if @onInsertTextArea}}
	did-insert @onInsertTextArea
  {{/if}}
/>
```

then maybe the modifiers provided by this library could silently handle undefined functions, so you could do:

```hbs
<div
  {{did-insert @onInsertTextArea}}
/>
```

and when `@onInsert` is `undefined` it wont throw an error, like it does now.

Either make the current modifiers silently handle `undefined` or make new ones to handle modifier function that might no always be provided. This is mostly for general components.

Another option might be to provide `-if` version of the modifiers:

```hbs
<div
  {{did-insert-if @onInsertTextArea @onInsertTextArea}}
/>
```

**Comment by rwjblue** [comment]
I would personally do something like this:

### With a backing class

```hbs
<div
  {{did-insert this.insertTextArea}}
/>
```

Where the implementation of `insertTextArea` being:

```js
@action
insertTextArea(element) {
  if (this.args.insertTextArea) {
    this.args.insertTextArea(element);
  }
}
```

### Without a backing class

```hbs
<div
  {{did-insert (if @insertTextArea @insertTextArea (empty-function))}}
>
```

And create a helper like:

```js
// app/helpers/empty-function.js

function emptyFunction() {};

export default Ember.Helper.helper(function() { return emptyFunction; });
```

**Comment by rwjblue** [comment]
FWIW, both of those solutions make it clear that it's ok that sometimes the argument isn't passed. Whereas by just allowing `undefined` to silently do nothing, we would be opening things up to a non-trivial number of accidental failure.

**Comment by emattias** [comment]
After writing this issue I discovered this solution:

```hbs
<div
  {{did-insert (optional @onDidInsertTextArea)}}
/>
```

Using the [optional](https://github.com/DockYard/ember-composable-helpers#optional) helper. This is my preferred solution.

I have no problem with this issue being closed now :)
