### ISSUE TITLE
Uses version of modifier manager capabilities that is deprecated in canary

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember-render-modifiers#32]
```
Versions of modifier manager capabilities prior to 3.22 have been deprecated. You must update to the 3.22 capabilities.
```

**Comment by boris-petrov** [comment]
Isn't the underlying issue in [ember-modifier](https://github.com/ember-modifier/ember-modifier/issues/75)?

**Comment by alexlafroscia** [comment]
I don't think that's the case here @boris-petrov -- this package does not depend on that one.

**Comment by jgadbois** [comment]
I'm getting deprecation warnings in Ember 3.26

**Comment by alexlafroscia** [comment]
#33 should resolve this once it's merged

**Comment by martinbarilik** [comment]
@alexlafroscia when it's gonna be ? :)

**Comment by alexlafroscia** [comment]
No idea 🤷‍♂️any context about that would be on the PR that I linked to, and that doesn't have an update within the last week.

**Comment by SergeAstapov** [comment]
#42 was merged which superseded #33, now new release should be cut and published.

**Comment by sandstrom** [comment]
awesome @SergeAstapov 🎉

**Comment by acorncom** [comment]
Looks like this can be closed
