### ISSUE TITLE
Octane needs types added in resolver

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember-render-modifiers#6]
at present, these need to be added manually:

```ts
  // required for @ember/element-modifiers
  modifier: { definitiveCollection: 'main' },
```

in src/resolver.js.

Whenever there are hooks for addons to do this themselves, this addon should add the modifier collection.

**Comment by rwjblue** [comment]
@NullVoxPopuli - Mind making a PR to ember-resolver to add this by default?

**Comment by rwjblue** [comment]
I think this is fixed...
