### ISSUE TITLE
Unexpected token '.' in Gitlab pipeline

### ISSUE THREAD

**Issue by Unkrass** [emberjs/ember-render-modifiers#62]
After installing ember-render-modifiers version 2.0.3 or 2.0.4 the local building process works fine, but the Gitlab pipeline fails with the error `Unexpected token '.'` and nothing else in the logs. We use a docker container in the pipeline that executes `ember build --environment=test`. Then it builds, cleans up and logs the error message.

Is there anything I can do to get more info about that error? Has anyone encountered that before?

**Comment by SergeAstapov** [comment]
@Unkrass I’ve seen this several times when used Node.js < 14 with fastboot and there was optional chaining somewhere in my code or in the deps.

Try adding `node: current` to `config/targets.js`

**Comment by Unkrass** [comment]
@SergeAstapov 
You're right. The Docker container in the pipeline was still on Node 12.16.1. I updated the config/targets.js file and now it succeeds. Thank you so much!

```
module.exports = {
  node: 'current',
  browsers
};
```
